package com.codementor.backend.export.pdf;

import com.lowagie.text.Document;
import com.lowagie.text.Element;
import com.lowagie.text.Font;
import com.lowagie.text.FontFactory;
import com.lowagie.text.Image;
import com.lowagie.text.Phrase;
import com.lowagie.text.Rectangle;
import com.lowagie.text.pdf.ColumnText;
import com.lowagie.text.pdf.PdfContentByte;
import com.lowagie.text.pdf.PdfPageEventHelper;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.pdf.PdfGState;

import java.awt.Color;
import java.io.InputStream;

public class PdfPageEvent extends PdfPageEventHelper {

    private Image logo;
    private Image watermarkLogo;

    @Override
    public void onOpenDocument(PdfWriter writer, Document document) {

        try {

            InputStream inputStream =
                    getClass()
                            .getClassLoader()
                            .getResourceAsStream("static/images/codementor-logo.png");

            if (inputStream != null) {

                byte[] bytes = inputStream.readAllBytes();

                logo = Image.getInstance(bytes);

                logo.scaleToFit(28, 28);

            }

        InputStream watermarkStream =
                getClass()
                        .getClassLoader()
                        .getResourceAsStream("static/images/brain-logo.png");

        if (watermarkStream != null) {

            byte[] watermarkBytes = watermarkStream.readAllBytes();

            watermarkLogo = Image.getInstance(watermarkBytes);

            watermarkLogo.scaleToFit(300, 300);
        }


        } catch (Exception ignored) {
        }

    }

@Override
public void onEndPage(PdfWriter writer, Document document) {

    if (writer.getPageNumber() == 1) {
        return;
    }

    PdfContentByte canvas = writer.getDirectContent();

    // Draw watermark first (behind everything)
    drawWatermark(canvas, document);

    // Draw header
    drawHeader(canvas, document);

    // Draw footer
    drawFooter(canvas, document, writer);

}
    
    private void drawHeader(
            PdfContentByte canvas,
            Document document
    ) {

        try {

            if (logo != null) {

                logo.setAbsolutePosition(
                        document.left(),
                        document.top() + 20
                );

                canvas.addImage(logo);

            }

            Font font =
                    FontFactory.getFont(
                            FontFactory.HELVETICA_BOLD,
                            11,
                            new Color(25, 55, 109)
                    );

            ColumnText.showTextAligned(
                    canvas,
                    Element.ALIGN_LEFT,
                    new Phrase(
                            "CodeMentorAI Developer Report",
                            font
                    ),
                    document.left() + 35,
                    document.top() + 30,
                    0
            );

            canvas.setColorStroke(new Color(25, 55, 109));

            canvas.moveTo(
                    document.left(),
                    document.top() + 15
            );

            canvas.lineTo(
                    document.right(),
                    document.top() + 15
            );

            canvas.stroke();

        } catch (Exception ignored) {
        }

    }

    private void drawFooter(
            PdfContentByte canvas,
            Document document,
            PdfWriter writer
    ) {

        Font font =
                FontFactory.getFont(
                        FontFactory.HELVETICA,
                        9,
                        Color.GRAY
                );

        canvas.setColorStroke(Color.LIGHT_GRAY);

        canvas.moveTo(
                document.left(),
                document.bottom() - 10
        );

        canvas.lineTo(
                document.right(),
                document.bottom() - 10
        );

        canvas.stroke();

        ColumnText.showTextAligned(
                canvas,
                Element.ALIGN_LEFT,
                new Phrase(
                        "Generated by CodeMentorAI",
                        font
                ),
                document.left(),
                document.bottom() - 25,
                0
        );

        ColumnText.showTextAligned(
                canvas,
                Element.ALIGN_RIGHT,
                new Phrase(
                        "Page " + writer.getPageNumber(),
                        font
                ),
                document.right(),
                document.bottom() - 25,
                0
        );

    }

    private void drawWatermark(
            PdfContentByte canvas,
            Document document
    ) {

        if (watermarkLogo == null) {
            return;
        }

        try {

            PdfGState state = new PdfGState();
            state.setFillOpacity(0.08f);

            canvas.saveState();
            canvas.setGState(state);

            float x =
                    (document.right() - watermarkLogo.getScaledWidth()) / 2;

            float y =
                    (document.top() + document.bottom()
                            - watermarkLogo.getScaledHeight()) / 2;

            watermarkLogo.setAbsolutePosition(x, y);

            canvas.addImage(watermarkLogo);

            canvas.restoreState();

        } catch (Exception ignored) {
        }

    }

}