spring.application.name=backend

# =====================================
# SERVER
# =====================================

server.port=${PORT:8080}

# =====================================
# POSTGRESQL
# =====================================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/postgres}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# =====================================
# JPA
# =====================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

debug=false

# =====================================
# JWT
# =====================================

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# =====================================
# GEMINI
# =====================================

gemini.api.key=${GEMINI_API_KEY}

# =====================================
# IMPORT LOCAL SECRETS
# =====================================

spring.config.import=optional:classpath:application-secrets.properties

# =====================================
# FRONTEND
# =====================================

frontend.url=${FRONTEND_URL:http://localhost:5173}


# =====================================
# CODE EXECUTION
# =====================================

execution.provider=${EXECUTION_PROVIDER:remote}

execution.judge0.url=${JUDGE0_URL:https://ce.judge0.com}
