spring.application.name=backend

# =====================================
# SERVER
# =====================================

server.port=8080

# =====================================
# POSTGRESQL
# =====================================

spring.datasource.url=jdbc:postgresql://localhost:5433/postgres
spring.datasource.username=postgres
spring.datasource.password=Aditya@007

# =====================================
# JPA
# =====================================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

debug=true

# =====================================
# JWT
# =====================================

jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# =====================================
# GEMINI
# =====================================

gemini.api.key=${GEMINI_API_KEY}

# =====================================
# IMPORT LOCAL SECRETS
# =====================================

spring.config.import=optional:classpath:application-secrets.properties


frontend.url=http://localhost:5173