import {
  FiAward,
  FiTarget,
  FiTrendingUp,
  FiStar,
} from "react-icons/fi";

interface Achievement {
  title: string;
  description: string;
  icon: React.ElementType;
  color: string;
}

const achievements: Achievement[] = [
  {
    title: "TCS CodeVita",
    description: "Global Rank 7018",
    icon: FiAward,
    color: "text-yellow-500",
  },
  {
    title: "LeetCode Streak",
    description: "240+ Days",
    icon: FiTrendingUp,
    color: "text-orange-500",
  },
  {
    title: "Contest Rating",
    description: "1682 Rating",
    icon: FiTarget,
    color: "text-blue-500",
  },
  {
    title: "AI Interview Ready",
    description: "Generated by CodeMentorAI",
    icon: FiStar,
    color: "text-emerald-500",
  },
];

export default function AchievementsCard() {
  return (
    <section className="app-surface app-border rounded-2xl p-6">

      <div className="mb-6">

        <h2 className="text-xl font-bold">
          Achievements
        </h2>

        <p className="app-text-secondary mt-2">
          Milestones unlocked during your coding journey.
        </p>

      </div>

      <div className="space-y-4">

        {achievements.map((achievement) => {
          const Icon = achievement.icon;

          return (
            <div
              key={achievement.title}
              className="flex items-center gap-4 rounded-xl border border-slate-700/40 p-4 transition hover:border-blue-500"
            >
              <div
                className={`flex h-12 w-12 items-center justify-center rounded-xl bg-slate-800 ${achievement.color}`}
              >
                <Icon className="text-xl" />
              </div>

              <div>

                <h3 className="font-semibold">
                  {achievement.title}
                </h3>

                <p className="app-text-secondary text-sm">
                  {achievement.description}
                </p>

              </div>

            </div>
          );
        })}

      </div>

    </section>
  );
}