import {
  FiCpu,
  FiTrendingUp,
  FiCheckCircle,
  FiTarget,
  FiRefreshCw,
} from "react-icons/fi";

import type { AiDeveloperSummary } from "../../types/portfolioAi";

interface Props {
  data: AiDeveloperSummary;
  onRegenerate?: () => void;
}

export default function AIDeveloperSummaryCard({
  data,
  onRegenerate,
}: Props) {
  return (
    <section className="app-surface app-border rounded-3xl p-8">

      {/* Header */}

      <div className="flex items-start justify-between">

        <div>

          <div className="flex items-center gap-3">

            <FiCpu className="text-3xl text-violet-400" />

            <div>

              <h2 className="text-2xl font-bold">
                AI Developer Summary
              </h2>

              <p className="mt-1 app-text-secondary">
                Personalized developer profile generated by CodeMentorAI.
              </p>

            </div>

          </div>

        </div>

        <button
          onClick={onRegenerate}
          className="inline-flex items-center gap-2 rounded-xl border border-slate-700 px-5 py-3 transition hover:border-violet-500 hover:text-violet-400"
        >
          <FiRefreshCw />
          Regenerate
        </button>

      </div>

      {/* Summary */}

      <div className="mt-8 rounded-2xl border border-violet-500/20 bg-violet-500/5 p-6">

        <h3 className="mb-4 text-lg font-semibold">
          Developer Summary
        </h3>

        <p className="leading-8 app-text-secondary whitespace-pre-line">
          {data.summary}
        </p>

      </div>

      {/* Strengths + Growth */}

      <div className="mt-8 grid gap-6 lg:grid-cols-2">

        <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-6">

          <div className="mb-5 flex items-center gap-2">

            <FiCheckCircle className="text-emerald-400" />

            <h3 className="font-semibold">
              Top Strengths
            </h3>

          </div>

          <div className="space-y-3">

            {data.strengths.map((strength) => (

              <div
                key={strength}
                className="flex items-center gap-3"
              >
                <FiCheckCircle className="text-emerald-400" />

                <span>{strength}</span>

              </div>

            ))}

          </div>

        </div>

        <div className="rounded-2xl border border-orange-500/20 bg-orange-500/5 p-6">

          <div className="mb-5 flex items-center gap-2">

            <FiTrendingUp className="text-orange-400" />

            <h3 className="font-semibold">
              Growth Areas
            </h3>

          </div>

          <div className="space-y-3">

            {data.growthAreas.map((area) => (

              <div
                key={area}
                className="flex items-center gap-3"
              >
                <FiTrendingUp className="text-orange-400" />

                <span>{area}</span>

              </div>

            ))}

          </div>

        </div>

      </div>

      {/* Recruiter */}

      <div className="mt-8 rounded-2xl border border-blue-500/20 bg-blue-500/5 p-6">

        <div className="flex items-center justify-between">

          <div>

            <h3 className="flex items-center gap-2 text-lg font-semibold">

              <FiTarget />

              Recruiter Match

            </h3>

            <p className="mt-2 app-text-secondary">

              Recommended Role:
              <span className="ml-2 font-semibold text-white">
                {data.recommendedRole}
              </span>

            </p>

          </div>

          <div className="text-right">

            <p className="text-4xl font-bold text-blue-400">
              {data.recruiterMatch}%
            </p>

          </div>

        </div>

        <div className="mt-5 h-3 overflow-hidden rounded-full bg-slate-700">

          <div
            className="h-full rounded-full bg-blue-500 transition-all duration-700"
            style={{
              width: `${data.recruiterMatch}%`,
            }}
          />

        </div>

      </div>

    </section>
  );
}