import {
  FiTrendingUp,
  FiTarget,
  FiAward,
  FiArrowRight,
} from "react-icons/fi";

interface AISummaryCardProps {
  growthSummary: string;
  recommendedNextAction: string;
  achievements: string[];
}

export default function AISummaryCard({
  growthSummary,
  recommendedNextAction,
  achievements,
}: AISummaryCardProps) {

  return (

    <section className="app-surface app-border rounded-2xl p-6">

      <div className="mb-6">

        <h2 className="text-2xl font-bold">

          🤖 AI Career Analysis

        </h2>

        <p className="app-text-secondary mt-2">

          Personalized insights generated by CodeMentorAI.

        </p>

      </div>

      <div className="space-y-6">

        {/* Growth Summary */}

        <div className="rounded-2xl border border-blue-500/20 bg-blue-500/5 p-5">

          <div className="mb-3 flex items-center gap-2">

            <FiTrendingUp className="text-blue-500" />

            <h3 className="font-semibold">

              Current Growth

            </h3>

          </div>

          <p className="leading-7">

            {growthSummary}

          </p>

        </div>

        {/* Next Recommendation */}

        <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-5">

          <div className="mb-3 flex items-center gap-2">

            <FiTarget className="text-emerald-500" />

            <h3 className="font-semibold">

              Recommended Next Action

            </h3>

          </div>

          <div className="flex items-center justify-between">

            <p>

              {recommendedNextAction}

            </p>

            <FiArrowRight className="text-emerald-500 text-xl" />

          </div>

        </div>

        {/* Achievements */}

        <div>

          <div className="mb-4 flex items-center gap-2">

            <FiAward className="text-yellow-500" />

            <h3 className="font-semibold">

              AI Achievements

            </h3>

          </div>

          <div className="space-y-3">

            {achievements.map((achievement) => (

              <div
                key={achievement}
                className="flex items-center gap-3 rounded-xl border border-yellow-500/20 bg-yellow-500/5 p-3"
              >

                <FiAward className="text-yellow-500" />

                <span>

                  {achievement}

                </span>

              </div>

            ))}

          </div>

        </div>

      </div>

    </section>

  );

}